### ISSUE TITLE
Index Queries

### ISSUE THREAD

**Issue by UWPA** [rogeraabbccdd/Kento-Rankme#114]
When using this plugin I've actually been suspended from a host because running Rankme through multiple servers caused their MySQL to crash due to the amount of queries coming in and out that it locked up the entire table every time it saved names/ips as it scanned the entire file.

**Comment by TandelK** [comment]
There is no other way to store ranks the only option is via MySQL Database or SQL lite but everyone knows MySQL is better way to store things. I would recommend you to please find a host that does not have restrictions.  Most of the CSGO Community Servers hosts their own SQL Databases as its given completes freedom to connect update and delete things immediately  instead of relying on some other host. You can use DigitalOcean , Amazon AWS or other services just for own Databases.
