### ISSUE TITLE
Installed rankme but doesn't work

### ISSUE THREAD

**Issue by Hankeei** [rogeraabbccdd/Kento-Rankme#149]
Hello Im new to creating csgo server
I try to install rankme into my server but it doesn't work for me
I installed the latest sourcemod and meta mod into my server
the rankme doesnt create .cfg or work ingame
same as some other mod which doesnt work too
what can I do or what step I missed
I use ubuntu to host the server so yea

**Comment by borzaka** [comment]
Your problem is not Rankme specific, it's probably SourceMod or even a server problem.
Try to ask you questions in the forum, or on the Discord channel.
Forum: https://forums.alliedmods.net/forumdisplay.php?f=52
Discord: https://discord.gg/HUc67zN

TODO:
Can you even connect your server?
Check server and SourceMod logs.
Bring these information to the corresponding channels.

**Comment by Hankeei** [comment]
I checked and I can connect to my server
I followed the step in youtube to install the plugin
may I ask that where can I check my sourcemod log?

**Comment by borzaka** [comment]
SourceMod logs:
`csgo/addons/sourcemod/logs/`

Server logs:
`csgo/logs/`

Have you restarted your server after installing mods?

Please, if you have further questions, ask somewhere else, because here you should only raise Rankme related issues, not basic server management stuff.
In other words: don't spam with offtopic questions this issue tracker.

**Comment by Hankeei** [comment]
ok sorry about that I ask off topic question at here
I check all log file and I see no log for no reasons , I restarted my server after installing my mod so yea

**Comment by borzaka** [comment]
What's happening when you connect to your server?
How did you install the SourceMod? Did you place everything to the corresponding folders?
https://wiki.alliedmods.net/Installing_SourceMod

What you see when entering these commands to the console:
`sm plugins list`
`meta list`

Other stupid questions to ask, because you haven't provide much information:
Have you installed MetaMod as well?

If you ask for help, you should provide as many information as possible, because without that anyone can just guessing...
